spring:
  application:
    name: climatehub-ms-notification
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
server:
  port: ${APP_PORT:8081}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: senhaultrasecreta
  expiration: 3600000 # 1 hora

logging:
  level:
    root: INFO
    com.mercadolibre.itarc.climatehub_ms_notification: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: INFO
